### ISSUE TITLE
Issue in cart when logging in 

### ISSUE THREAD

**Issue by duckchip** [lsretailomni/lsmag-two#28]
### Preconditions (*)

1. Magento 2.3.5
2. lsretail v1.6.1 

### Steps to reproduce (*)

1. You start as a guest and you put something in the cart 
2. Log in with an existing account
3. Log out
4. Log in again

### Expected result (*)

1. No issues

### Actual result (*)

1. a console log is thrown with the following error:
```
<b>Fatal error</b>:  Uncaught Error: Call to a member function getOrderLines() on null in /vendor/lsretail/lsmag-two/src/Omni/Helper/BasketHelper.php:893
Stack trace:
#0 /vendor/lsretail/lsmag-two/src/Omni/Plugin/Checkout/CustomerData/Cart.php(101): Ls\Omni\Helper\BasketHelper->getItemRowTotal(Object(Magento\Quote\Model\Quote\Item\Interceptor))
#1 /vendor/magento/framework/Interception/Interceptor.php(146): Ls\Omni\Plugin\Checkout\CustomerData\Cart->afterGetSectionData(Object(Magento\Checkout\CustomerData\Cart\Interceptor), Array)
#2 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\CustomerData\Cart\Interceptor->Magento\Framework\Interception{closure}()
#3 /generated/code/Magento/Checkout/CustomerData/Cart/Interceptor.php(26): Magento\Checkout\CustomerData\Cart\Interceptor->___callPlugins('getSectionData in <b>/vendor/lsretail/lsmag-two/src/Omni/Helper/BasketHelper.php</b> on line <b>893</b><br />
```

There should be done a better check on the order lines.

**Comment by lsretailomni** [comment]
This has been fixed in https://github.com/lsretailomni/lsmag-two/pull/29. closing this.
